# Generated by Django 5.2.8 on 2025-11-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_document_options_document_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
